project:
  type: website
  output-dir: docs

website:
  title: "Blog Marcelo Chávez"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: hoja_de_vida.qmd
        text: Hoja de Vida
      - href: contacto.qmd
        text: Contáctame
      - href: CaracterizacionEcologica.qmd
        text: Índice Multivariante

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

